import { ListingResponse } from "./api-contracts/responses/Listing";

export const listings: ListingResponse[] = [
  {
    id: 1,
    name: "Item 1",
    description: "This is item 1",
    image_name: "item1.jpg",
    image_url: "https://picsum.photos/200",
    auction_type: "dutch",
    status: "ongoing",
    current_bid_price: 100,
    end_time: "1701916799000",
  },
  {
    id: 2,
    name: "Item 2",
    description: "This is item 2",
    image_name: "item2.jpg",
    image_url: "https://picsum.photos/200",
    auction_type: "forward",
    status: "ongoing",
    current_bid_price: 200,
    end_time: "1701916799000",
  },
  {
    id: 3,
    name: "Item 3",
    description: "This is item 3",
    image_name: "item3.jpg",
    image_url: "https://picsum.photos/200",
    auction_type: "dutch",
    status: "ongoing",
    current_bid_price: 300,
    end_time: "1701916799000",
  },
  {
    id: 4,
    name: "Item 4",
    description: "This is item 4",
    image_name: "item4.jpg",
    image_url: "https://picsum.photos/200",
    auction_type: "forward",
    status: "ongoing",
    current_bid_price: 400,
    end_time: "1701916799000",
  },
  {
    id: 5,
    name: "Item 5",
    description: "This is item 5",
    image_name: "item5.jpg",
    image_url: "https://picsum.photos/200",
    auction_type: "dutch",
    status: "ongoing",
    current_bid_price: 500,
    end_time: "1701916799000",
  },
  {
    id: 6,
    name: "Item 6",
    description: "This is item 6",
    image_name: "item6.jpg",
    image_url: "https://picsum.photos/200",
    auction_type: "forward",
    status: "ongoing",
    current_bid_price: 600,
    end_time: "1701916799000",
  },
];
