import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import { Inter } from 'next/font/google'
import LandingPage from './landing/LandingPage'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Auction Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/web/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="/web/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/web/favicon-16x16.png"/>
        <link rel="manifest" href="/web/site.webmanifest"/>
        <link rel="mask-icon" href="/web/safari-pinned-tab.svg" color="#5bbad5"/>
        <meta name="msapplication-TileColor" content="#da532c"/>
        <meta name="theme-color" content="#ffffff"></meta>
      </Head>

      <main className={inter.className}>
        <LandingPage />
      </main>
    </>
  )
}
